# Generated by Django 4.2.7 on 2023-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiak_sign', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
